dist: xenial

language: python

python:
  - 3.7.1
  - 3.8
  - 3.8.6
  - 3.9
  - 3.9.1

cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $HOME/.cache/matplotlib

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblapack-dev libopenblas-dev

# Install packages
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel setuptools
  - pip install Cython --install-option="--no-cython-compile"
  - pip install --upgrade numpy
  - pip install --upgrade scipy
  - pip install --upgrade pandas
  - pip install --upgrade coveralls
  - pip install --upgrade pytest
  - pip install --upgrade pytest-cov
  - pip install --upgrade pytest-mpl
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - pytest --cov hspfbintoolbox --doctest-modules --ignore=docsrc --mpl

after_success:
  - coveralls
