#!/bin/bash

program=hspfbintoolbox

pkgs="\
     setuptools \
     atlas \
     numpy \
     scipy \
     matplotlib \
     nose \
     dateutil \
     pandas \
     pip \
     coverage \
     flake8 \
     "

# pandas no longer supports 2.6
envs=(~/python_ves/python-2.7.13)

for env in ${envs[@]}; do
    echo "${env}"

    source "${env}"/bin/activate
    pip install --upgrade pip
    pip install wheel
    pip install --upgrade --only-binary pandas,scipy ${pkgs}
    pip uninstall -y ${program}
    rm -rf build
    python setup.py develop

    nosetests \
        --with-coverage \
        --cover-tests \
        --cover-package=${program} \
        --cover-branches \
        --cover-erase \
        -s
    deactivate
done

source "${env}"/bin/activate
coverage erase
coverage run `which nosetests`
coverage report --include="${program}/*" --omit="tests/*"
coverage html --include="${program}/*" --omit="tests/*"
flake8 ${program}/__init__.py ${program}/${program}.py --exit-zero
deactivate
