[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools-scm[simple]>=8",
    "setuptools>=80"
]

[project]
authors = [
    {email = "tim@cerazone.net", name = "Tim Cera"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules"
] # Get strings from http://pypi.python.org/pypi?%3Aaction=list_classifiers
dependencies = [
    "cltoolbox > 1.1.0",
    "dateparser",
    "numpy",
    "pandas[excel]",
    "pint",
    "pint-pandas",
    "pydantic",
    "scipy",
    "tabulate"
]
description = "Reads Hydrological Simulation Program - FORTRAN binary output files."
dynamic = ["readme", "version"]
keywords = [
    "binary",
    "hspf",
    "hydrologic",
    "model",
    "simulation"
]
license = {text = "BSD-3-Clause"}
name = "hspfbintoolbox"
requires-python = ">=3.10"

[project.scripts]
hspfbintoolbox = "hspfbintoolbox.hspfbintoolbox:main"

[project.urls]
bitbucket = "https://bitbucket.org/timcera/hspfbintoolbox/src/main/"
documentation = "https://timcera.bitbucket.io/hspfbintoolbox/docs/index.html#hspfbintoolbox-documentation"
github = "https://github.com/timcera/hspfbintoolbox"

[tool.check-manifest]
ignore = [
    ".coverage",
    ".deepsource.toml",
    ".ipynb_checkpoints/*",
    "docs/_function_autosummary/*"
]

[tool.commitizen]
multiline = true
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version = "9.0.12"
version_files = ["VERSION"]

[tool.isort]
profile = "black"

[tool.jupytext]
formats = "auto:percent"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
exclude = [
    "src/*/toolbox_utils/**/*.py"
]
fix = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort.import-heading]
first-party = "First party imports"
future = "Future imports"
local-folder = "Local folder imports"
standard-library = "Standard library imports"
third-party = "Third party imports"

[tool.setuptools]
include-package-data = true
license-files = ["LICENSE.txt"]

[tool.setuptools.dynamic]
readme = {file = "README.rst"}
version = {file = "VERSION"}

[tool.setuptools.packages.find]
where = ["src"]
